version: "2"
services:

  order:
    image: openlmis/order
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres
    ports:
      - "8765:5432"
    env_file: .env

  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/order:/var/log'
