version: "2"
services:

  fulfillment:
    image: openlmis/fulfillment
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        syslog-facility: "local1"
    depends_on: [log]
    env_file: .env

  log:
    image: openlmis/rsyslog
    ports:
      - "514:514"
    volumes:
      - '../logs/fulfillment:/var/log'
